% =========================================================================
% Post-Processing: Custom Region-Based FD Extraction
% =========================================================================

roi_mask_path = '/path/to/your/custom_roi_mask.nii';
[mask_data, mask_header] = y_Read(roi_mask_path);

% Loop through subjects to extract region-specific FD
for s = 1:length(Cfg.SubjectIDString)
    sub = Cfg.SubjectIDString{s};
    
    % Path to the 4D voxel-based FD maps generated by DPARSFA
    fd_vox_path = fullfile(Cfg.DataProcessDir, 'RealignParameter', sub, ['FDvox_', sub, '.nii']);
    
    if exist(fd_vox_path, 'file')
        [fd_data, fd_header] = y_Read(fd_vox_path);
        
        % Reshape data to 2D matrix (Voxels x Time)
        [X, Y, Z, T] = size(fd_data);
        fd_matrix = reshape(fd_data, X*Y*Z, T);
        mask_vector = reshape(mask_data, X*Y*Z, 1);
        
        % Extract voxels inside your ROI mask and take the spatial mean
        roi_fd_timecourse = mean(fd_matrix(mask_vector > 0, :), 1)';
        
        % Save out your custom region-based FD text file
        output_txt = fullfile(Cfg.DataProcessDir, 'RealignParameter', sub, ['mean_ROI_FDvox_', sub, '.txt']);
        save(output_txt, 'roi_fd_timecourse', '-ascii');
    else
        warning('Could not locate FDvox file for subject %s', sub);
    end
end